baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Nurfaiz Foat - Portfolio'
theme = 'neobrute'
homepage = "index"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

